- documentName: 'Across School: Dynamic Forms Module (basic)'
  fields:
    tag-line: 'From n00b to basic development with Dynamic Forms Module'
    date: '2018-09-13'
    location:
      street: Sint-Bartholomeusstraat
      zipCode: 2170
      city: Merksem
    schedule:
      morning:
        details: 'DataSet, Definitions and Documents'
        endTime: '08:00:00'
        startTime: '12:00:00'
      afternoon:
        details: 'Customizing list views, importing data'
        endTime: '13:00:00'
        startTime: '17:00:00'
    maximumNumberOfParticipants: 30
    registrationFee: 19.99
    registrationPossible: true
    discount: 0.05
    trainers:
    - -1
- documentName: 'Across School: Dynamic Forms Module (advanced)'
  fields:
    tag-line: 'Become a wizard and learn the ins and outs of the Dynamic Forms Module'
    date: '2018-10-22'
    location:
      street: Sint-Bartholomeusstraat
      zipCode: 2170
      city: Merksem
    schedule:
      morning:
        details: 'DataSet, Definitions and Documents with ACL'
        endTime: '08:00:00'
        startTime: '12:00:00'
      afternoon:
        details: 'DynamicDocumentWorkspace customizaitons'
        endTime: '13:00:00'
        startTime: '17:00:00'
    maximumNumberOfParticipants: 10
    registrationFee: 29.99
    registrationPossible: false
    discount: 0.20
    trainers:
    - -1
    - -2
