document-definition:
  name: Training
  types:
  - id: schedule-entry
    base-type: fieldset
    fields:
    - id: startTime
      type: time
    - id: endTime
      type: time
    - id: details
      type: text
  content:
  - id: tag-line
    label: Call to action
    type: string
  - id: date
    label: Date of the training
    type: date
    validators:
    - required
    messages:
      description: When will the training take place?
  - id: trainers
    type: "@user[]"
    attributes:
      options-query: roles contains ROLE_TRAINER
  - id: location
    type: fieldset
    fields:
    - id: street
      type: string
    - id: zipCode
      type: string
    - id: city
      type: string
  - id: registrationFee
    type: currency(EUR)
    validators:
    - required
  - id: discount
    type: percentage(100)
    validators:
    - required
  - id: maximumNumberOfParticipants
    type: number
  - id: registrationPossible
    label: Participants can register
    type: boolean
    messages:
      tooltip: Users will be allowed to register via the frontend when checked.
  - id: schedule
    label: Schedule details
    type: fieldset
    fields:
    - id: morning
      label: Morning schedule
      type: schedule-entry
    - id: afternoon
      label: Afternoon schedule
      type: schedule-entry
